#!/bin/bash
#########################################################################
## Process tested in Windows, using Cygwin                             ##
## other than the default of the instalation you will need to install: ##
## -> wget                                                             ##
## -> unzip                                                            ##
## -> md5deep (as there is no md5sum or cksum on Cygwin)               ##
## -> database client MySQL                                            ##
## you can select by searching for them in the Cygwin packages during  ##
## the install.                                                        ##
#########################################################################

### Environment ###
STARTTIME=$(date +%s)
## for Linux: CHKSUM_CMD=md5sum
## for Windows Cygwin you may use alternate: http://md5deep.sourceforge.net
## cksum should be available in all Unix versions, leave it blank to force a refresh everytime it runs
## but that will avoid the overhead and I/O generated by this functionality
CHKSUM_CMD=md5sum
MYSQL_DIR=/usr/bin/
# for simplicity I added the MYSQL bin path to the Windows 
# path environment variable, for Windows set it to ""
#MYSQL_DIR=""
# after MySQL 5.6+ we depend on the mysql_config_editor to
# save the connections credentials (host, user, password)
# then we can use: --login-path={name of your connection}
MYSQL_LOGINPATH=local
#MySQL user, password, host (Server)
MYSQL_USER=eanuser
MYSQL_PASS=Passw@rd1
MYSQL_HOST=localhost
MYSQL_DB=eanprod
# home directory of the user (in our case "eanuser")
HOME_DIR=/home/eanuser
# protocol TCP All, SOCKET Unix only, PIPE Windows only, MEMORY Windows only
MYSQL_PROTOCOL=SOCKET
# 3336 as default,MAC using MAMP is 8889
MYSQL_PORT=3306
## directory under HOME_DIR
FILES_DIR=eanfiles
## retention period in DAYS for the log of ActivePropertyList changes
LOG_DAYS=30

## Import files ###
#####################################
# the list should match the tables ##
# created by create_ean.sql script ##
#####################################
FILES=(
ActivePropertyList
AirportCoordinatesList
AliasRegionList
AreaAttractionsList
AttributeList
ChainList
CityCoordinatesList
CountryList
DiningDescriptionList
HotelImageList
NeighborhoodCoordinatesList
ParentRegionList
PointsOfInterestCoordinatesList
PolicyDescriptionList
PropertyAttributeLink
PropertyDescriptionList
PropertyTypeList
RecreationDescriptionList
RegionCenterCoordinatesList
RegionEANHotelIDMapping
RoomTypeList
SpaDescriptionList
WhatToExpectList
#
# minorRev=25 added files
#
PropertyLocationList
PropertyAmenitiesList
PropertyRoomsList
PropertyBusinessAmenitiesList
PropertyNationalRatingsList
PropertyFeesList
PropertyMandatoryFeesList
PropertyRenovationsList
### Special File for Authorized Partners ONLY
ActivePropertyBusinessModel
## <BusinessModelMask> 	<Availability Offered>
## 1 	Expedia Collect only
## 2 	Hotel Collect only
## 3 	Both (ETP)
##########################
#
# To Add a language set, use this as a reference
#

ActivePropertyList_es_ES
AliasRegionList_es_ES
AreaAttractionsList_es_ES
AttributeList_es_ES
CountryList_es_ES
DiningDescriptionList_es_ES
PolicyDescriptionList_es_ES
PropertyAttributeLink_es_ES
PropertyDescriptionList_es_ES
PropertyTypeList_es_ES
RecreationDescriptionList_es_ES
RegionList_es_ES
RoomTypeList_es_ES
SpaDescriptionList_es_ES
WhatToExpectList_es_ES
PropertyLocationList_es_ES
PropertyAmenitiesList_es_ES
PropertyRoomsList_es_ES
PropertyBusinessAmenitiesList_es_ES
PropertyNationalRatingsList_es_ES
PropertyFeesList_es_ES
PropertyMandatoryFeesList_es_ES
PropertyRenovationsList_es_ES

ActivePropertyList_de_DE
AliasRegionList_de_DE
AreaAttractionsList_de_DE
AttributeList_de_DE
CountryList_de_DE
DiningDescriptionList_de_DE
PolicyDescriptionList_de_DE
PropertyAttributeLink_de_DE
PropertyDescriptionList_de_DE
PropertyTypeList_de_DE
RecreationDescriptionList_de_DE
RegionList_de_DE
RoomTypeList_de_DE
SpaDescriptionList_de_DE
WhatToExpectList_de_DE
PropertyLocationList_de_DE
PropertyAmenitiesList_de_DE
PropertyRoomsList_de_DE
PropertyBusinessAmenitiesList_de_DE
PropertyNationalRatingsList_de_DE
PropertyFeesList_de_DE
PropertyMandatoryFeesList_de_DE
PropertyRenovationsList_de_DE

ActivePropertyList_fr_FR
AliasRegionList_fr_FR
AreaAttractionsList_fr_FR
AttributeList_fr_FR
CountryList_fr_FR
DiningDescriptionList_fr_FR
PolicyDescriptionList_fr_FR
PropertyAttributeLink_fr_FR
PropertyDescriptionList_fr_FR
PropertyTypeList_fr_FR
RecreationDescriptionList_fr_FR
RegionList_fr_FR
RoomTypeList_fr_FR
SpaDescriptionList_fr_FR
WhatToExpectList_fr_FR
PropertyLocationList_fr_FR
PropertyAmenitiesList_fr_FR
PropertyRoomsList_fr_FR
PropertyBusinessAmenitiesList_fr_FR
PropertyNationalRatingsList_fr_FR
PropertyFeesList_fr_FR
PropertyMandatoryFeesList_fr_FR
PropertyRenovationsList_fr_FR

ActivePropertyList_nl_NL
AliasRegionList_nl_NL
AreaAttractionsList_nl_NL
AttributeList_nl_NL
CountryList_nl_NL
DiningDescriptionList_nl_NL
PolicyDescriptionList_nl_NL
PropertyAttributeLink_nl_NL
PropertyDescriptionList_nl_NL
PropertyTypeList_nl_NL
RecreationDescriptionList_nl_NL
RegionList_nl_NL
RoomTypeList_nl_NL
SpaDescriptionList_nl_NL
WhatToExpectList_nl_NL
PropertyLocationList_nl_NL
PropertyAmenitiesList_nl_NL
PropertyRoomsList_nl_NL
PropertyBusinessAmenitiesList_nl_NL
PropertyNationalRatingsList_nl_NL
PropertyFeesList_nl_NL
PropertyMandatoryFeesList_nl_NL
PropertyRenovationsList_nl_NL

ActivePropertyList_cs_CZ
AliasRegionList_cs_CZ
AreaAttractionsList_cs_CZ
AttributeList_cs_CZ
CountryList_cs_CZ
DiningDescriptionList_cs_CZ
PolicyDescriptionList_cs_CZ
PropertyAttributeLink_cs_CZ
PropertyDescriptionList_cs_CZ
PropertyTypeList_cs_CZ
RecreationDescriptionList_cs_CZ
RegionList_cs_CZ
RoomTypeList_cs_CZ
SpaDescriptionList_cs_CZ
WhatToExpectList_cs_CZ
PropertyLocationList_cs_CZ
PropertyAmenitiesList_cs_CZ
PropertyRoomsList_cs_CZ
PropertyBusinessAmenitiesList_cs_CZ
PropertyNationalRatingsList_cs_CZ
PropertyFeesList_cs_CZ
PropertyMandatoryFeesList_cs_CZ
PropertyRenovationsList_cs_CZ

ActivePropertyList_da_DK
AliasRegionList_da_DK
AreaAttractionsList_da_DK
AttributeList_da_DK
CountryList_da_DK
DiningDescriptionList_da_DK
PolicyDescriptionList_da_DK
PropertyAttributeLink_da_DK
PropertyDescriptionList_da_DK
PropertyTypeList_da_DK
RecreationDescriptionList_da_DK
RegionList_da_DK
RoomTypeList_da_DK
SpaDescriptionList_da_DK
WhatToExpectList_da_DK
PropertyLocationList_da_DK
PropertyAmenitiesList_da_DK
PropertyRoomsList_da_DK
PropertyBusinessAmenitiesList_da_DK
PropertyNationalRatingsList_da_DK
PropertyFeesList_da_DK
PropertyMandatoryFeesList_da_DK
PropertyRenovationsList_da_DK

ActivePropertyList_el_GR
AliasRegionList_el_GR
AreaAttractionsList_el_GR
AttributeList_el_GR
CountryList_el_GR
DiningDescriptionList_el_GR
PolicyDescriptionList_el_GR
PropertyAttributeLink_el_GR
PropertyDescriptionList_el_GR
PropertyTypeList_el_GR
RecreationDescriptionList_el_GR
RegionList_el_GR
RoomTypeList_el_GR
SpaDescriptionList_el_GR
WhatToExpectList_el_GR
PropertyLocationList_el_GR
PropertyAmenitiesList_el_GR
PropertyRoomsList_el_GR
PropertyBusinessAmenitiesList_el_GR
PropertyNationalRatingsList_el_GR
PropertyFeesList_el_GR
PropertyMandatoryFeesList_el_GR
PropertyRenovationsList_el_GR

ActivePropertyList_hu_HU
AliasRegionList_hu_HU
AreaAttractionsList_hu_HU
AttributeList_hu_HU
CountryList_hu_HU
DiningDescriptionList_hu_HU
PolicyDescriptionList_hu_HU
PropertyAttributeLink_hu_HU
PropertyDescriptionList_hu_HU
PropertyTypeList_hu_HU
RecreationDescriptionList_hu_HU
RegionList_hu_HU
RoomTypeList_hu_HU
SpaDescriptionList_hu_HU
WhatToExpectList_hu_HU
PropertyLocationList_hu_HU
PropertyAmenitiesList_hu_HU
PropertyRoomsList_hu_HU
PropertyBusinessAmenitiesList_hu_HU
PropertyNationalRatingsList_hu_HU
PropertyFeesList_hu_HU
PropertyMandatoryFeesList_hu_HU
PropertyRenovationsList_hu_HU

ActivePropertyList_it_IT
AliasRegionList_it_IT
AreaAttractionsList_it_IT
AttributeList_it_IT
CountryList_it_IT
DiningDescriptionList_it_IT
PolicyDescriptionList_it_IT
PropertyAttributeLink_it_IT
PropertyDescriptionList_it_IT
PropertyTypeList_it_IT
RecreationDescriptionList_it_IT
RegionList_it_IT
RoomTypeList_it_IT
SpaDescriptionList_it_IT
WhatToExpectList_it_IT
PropertyLocationList_it_IT
PropertyAmenitiesList_it_IT
PropertyRoomsList_it_IT
PropertyBusinessAmenitiesList_it_IT
PropertyNationalRatingsList_it_IT
PropertyFeesList_it_IT
PropertyMandatoryFeesList_it_IT
PropertyRenovationsList_it_IT

ActivePropertyList_lt_LT
AliasRegionList_lt_LT
AreaAttractionsList_lt_LT
AttributeList_lt_LT
CountryList_lt_LT
DiningDescriptionList_lt_LT
PolicyDescriptionList_lt_LT
PropertyAttributeLink_lt_LT
PropertyDescriptionList_lt_LT
PropertyTypeList_lt_LT
RecreationDescriptionList_lt_LT
RegionList_lt_LT
RoomTypeList_lt_LT
SpaDescriptionList_lt_LT
WhatToExpectList_lt_LT
PropertyLocationList_lt_LT
PropertyAmenitiesList_lt_LT
PropertyRoomsList_lt_LT
PropertyBusinessAmenitiesList_lt_LT
PropertyNationalRatingsList_lt_LT
PropertyFeesList_lt_LT
PropertyMandatoryFeesList_lt_LT
PropertyRenovationsList_lt_LT

ActivePropertyList_no_NO
AliasRegionList_no_NO
AreaAttractionsList_no_NO
AttributeList_no_NO
CountryList_no_NO
DiningDescriptionList_no_NO
PolicyDescriptionList_no_NO
PropertyAttributeLink_no_NO
PropertyDescriptionList_no_NO
PropertyTypeList_no_NO
RecreationDescriptionList_no_NO
RegionList_no_NO
RoomTypeList_no_NO
SpaDescriptionList_no_NO
WhatToExpectList_no_NO
PropertyLocationList_no_NO
PropertyAmenitiesList_no_NO
PropertyRoomsList_no_NO
PropertyBusinessAmenitiesList_no_NO
PropertyNationalRatingsList_no_NO
PropertyFeesList_no_NO
PropertyMandatoryFeesList_no_NO
PropertyRenovationsList_no_NO

ActivePropertyList_pl_PL
AliasRegionList_pl_PL
AreaAttractionsList_pl_PL
AttributeList_pl_PL
CountryList_pl_PL
DiningDescriptionList_pl_PL
PolicyDescriptionList_pl_PL
PropertyAttributeLink_pl_PL
PropertyDescriptionList_pl_PL
PropertyTypeList_pl_PL
RecreationDescriptionList_pl_PL
RegionList_pl_PL
RoomTypeList_pl_PL
SpaDescriptionList_pl_PL
WhatToExpectList_pl_PL
PropertyLocationList_pl_PL
PropertyAmenitiesList_pl_PL
PropertyRoomsList_pl_PL
PropertyBusinessAmenitiesList_pl_PL
PropertyNationalRatingsList_pl_PL
PropertyFeesList_pl_PL
PropertyMandatoryFeesList_pl_PL
PropertyRenovationsList_pl_PL

ActivePropertyList_pt_PT
AliasRegionList_pt_PT
AreaAttractionsList_pt_PT
AttributeList_pt_PT
CountryList_pt_PT
DiningDescriptionList_pt_PT
PolicyDescriptionList_pt_PT
PropertyAttributeLink_pt_PT
PropertyDescriptionList_pt_PT
PropertyTypeList_pt_PT
RecreationDescriptionList_pt_PT
RegionList_pt_PT
RoomTypeList_pt_PT
SpaDescriptionList_pt_PT
WhatToExpectList_pt_PT
PropertyLocationList_pt_PT
PropertyAmenitiesList_pt_PT
PropertyRoomsList_pt_PT
PropertyBusinessAmenitiesList_pt_PT
PropertyNationalRatingsList_pt_PT
PropertyFeesList_pt_PT
PropertyMandatoryFeesList_pt_PT
PropertyRenovationsList_pt_PT

ActivePropertyList_sv_SE
AliasRegionList_sv_SE
AreaAttractionsList_sv_SE
AttributeList_sv_SE
CountryList_sv_SE
DiningDescriptionList_sv_SE
PolicyDescriptionList_sv_SE
PropertyAttributeLink_sv_SE
PropertyDescriptionList_sv_SE
PropertyTypeList_sv_SE
RecreationDescriptionList_sv_SE
RegionList_sv_SE
RoomTypeList_sv_SE
SpaDescriptionList_sv_SE
WhatToExpectList_sv_SE
PropertyLocationList_sv_SE
PropertyAmenitiesList_sv_SE
PropertyRoomsList_sv_SE
PropertyBusinessAmenitiesList_sv_SE
PropertyNationalRatingsList_sv_SE
PropertyFeesList_sv_SE
PropertyMandatoryFeesList_sv_SE
PropertyRenovationsList_sv_SE

)

## home where the process will execute
#cd C:/data/EAN/DEV/database
## this will be CRONed so it needs the working directory absolute path
## change to your user home directory
cd ${HOME_DIR}

echo "Starting at working directory..."
pwd
## create subdirectory if required
if [ ! -d ${FILES_DIR} ]; then
   echo "creating download files directory..."
   mkdir ${FILES_DIR}
fi

## all clear, move into the working directory
cd ${HOME_DIR}

echo "Starting at working directory..."
pwd
## create subdirectory if required
if [ ! -d ${FILES_DIR} ]; then
   echo "creating download files directory..."
   mkdir ${FILES_DIR}
fi

## all clear, move into the working directory
cd ${FILES_DIR}

### Parameters that you may need:
### If you use LOW_PRIORITY, execution of the LOAD DATA statement is delayed until no other clients are reading from the table.
CMD_MYSQL="${MYSQL_DIR}mysql  --local-infile=1 --default-character-set=utf8 --protocol=${MYSQL_PROTOCOL} --port=${MYSQL_PORT} --user=${MYSQL_USER} --password=${MYSQL_PASS} --host=${MYSQL_HOST} --database=${MYSQL_DB}"
# for version 5.6.6+ you will need this line instead to use stored credentials
#CMD_MYSQL="${MYSQL_DIR}mysql --login-path=${MYSQL_LOGINPATH} --local-infile=1 --default-character-set=utf8 --protocol=${MYSQL_PROTOCOL} --port=${MYSQL_PORT} --database=${MYSQL_DB}"
#

echo "Running Extras ... Stored Procedures..."
### Run stored procedures as required for extra functionality       ###
### you can use this section for your own stuff                     ###
CMD_MYSQL="${MYSQL_DIR}mysql  --default-character-set=utf8 --protocol=${MYSQL_PROTOCOL} --port=${MYSQL_PORT} --user=${MYSQL_USER} --password=${MYSQL_PASS} --host=${MYSQL_HOST} --database=eanextras"
# for version 5.6.6+ you will need this line instead to use stored credentials
#CMD_MYSQL="${MYSQL_DIR}mysql --login-path=${MYSQL_LOGINPATH} --default-character-set=utf8 --protocol=${MYSQL_PROTOCOL} --port=${MYSQL_PORT} --database=eanextras"
#$CMD_MYSQL --execute="CALL eanextras.sp_fill_fasttextsearch();"
echo "Extras Stored Procedures done."


echo "Verify database against files..."
### Verify entries in tables against files ###
CMD_MYSQL="${MYSQL_DIR}mysqlshow --count ${MYSQL_DB} --protocol=${MYSQL_PROTOCOL} --port=${MYSQL_PORT} --user=${MYSQL_USER} --password=${MYSQL_PASS} --host=${MYSQL_HOST}"
# for version 5.6.6+ you will need this line instead to use stored credentials
#CMD_MYSQL="${MYSQL_DIR}mysqlshow --login-path=${MYSQL_LOGINPATH} --count ${MYSQL_DB} --protocol=${MYSQL_PROTOCOL} --port=${MYSQL_PORT} --user=${MYSQL_USER} --password=${MYSQL_PASS} --host=${MYSQL_HOST}"
$CMD_MYSQL

### find the amount of records per datafile
### should match to the amount of database records
echo "+---------------------------------+----------+------------+"
echo "|             File                |       Records         |"
echo "+---------------------------------+----------+------------+"
for FILE in ${FILES[@]}
do
## to count the number of output records minus the header
##    records=$(($(wc -l $FILE.txt | awk '{print $1}')-1))
   records=`wc -l < $FILE.txt | tr -d ' '`
   (( records-- ))
   { printf "|" && printf "%33s" $FILE && printf "|" && printf "%23d" $records && printf "|\n"; }
done
echo "+---------------------------------+----------+------------+"
echo "Verify done."

## display endtime for the script
ENDTIME=$(date +%s)
secs=$(( $ENDTIME - $STARTTIME ))
h=$(( secs / 3600 ))
m=$(( ( secs / 60 ) % 60 ))
s=$(( secs % 60 ))
printf "total script time: %02d:%02d:%02d\n" $h $m $s
echo "script (import_db.sh) done."